apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.botfront.api.appName }}
  name: {{ .Release.Name }}-api-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.botfront.api.appName }}
  type: NodePort
