apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Release.Name }}-secrets
type: "Opaque"
data:
  {{- if .Values.botfront.smtpUri }}
  MAIL_URL: {{ .Values.botfront.smtpUri | b64enc | quote }}
  {{- end }}
  MONGO_URL: {{ printf "mongodb://%s:%s@%s:%s/%s?%s" .Values.mongodb.mongodbUsername .Values.mongodb.mongodbPassword .Values.mongodb.mongodbHost .Values.mongodb.mongodbPort .Values.mongodb.mongodbDatabase .Values.mongodb.mongodbQueryString | b64enc | quote }}
  OPLOG_URL: {{ printf "mongodb://%s:%s@%s:%s/%s?%s" .Values.mongodb.mongodbOplogUsername .Values.mongodb.mongodbOplogPassword .Values.mongodb.mongodbHost .Values.mongodb.mongodbPort "local" .Values.mongodb.mongodbQueryString | b64enc | quote }}