apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.botfront.app.appName }}
  name: {{ .Release.Name }}-app-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.botfront.app.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.botfront.app.appName }}
    spec:
      containers:
      - env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              key: MONGO_URL
              name: {{ .Release.Name }}-secrets
        - name: MAIL_URL
          valueFrom:
            secretKeyRef:
              key: MAIL_URL
              name: {{ .Release.Name }}-secrets
        - name: OPLOG_URL
          valueFrom:
            secretKeyRef:
              key: OPLOG_URL
              name: {{ .Release.Name }}-secrets
        # - name: API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       key: API_KEY
              name: {{ .Release.Name }}-secrets
        - name: PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-app-config
            optional: false
        image: {{ .Values.botfront.app.image.name }}:{{ .Values.botfront.version }}
        imagePullPolicy: IfNotPresent
        name: {{ .Release.Name }}-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          {{- with .Values.botfront.app.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - mountPath: /app/models
          mountPropagation: None
          name: {{ .Release.Name }}-disk
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: {{ .Values.botfront.app.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.botfront.app.livenessProbe.periodSeconds }}
      restartPolicy: Always
      {{if .Values.botfront.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.botfront.imagePullSecret }}
      {{end }}
      volumes:
      - emptyDir: {}
        name: {{ .Release.Name }}-disk