{{- if .Values.botfront.webhooks.enabled -}}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ .Release.Name }}-api-config
data:
  PORT: "8080"
  APPLICATION_APP_LOG_TRANSPORT: {{ .Values.botfront.logs.transport | quote }}
  APPLICATION_APP_LOG_LEVEL: {{ .Values.botfront.logs.level | quote }}
  {{if .Values.kubernetesApi.baseUrl }}
  K8S_BASE_URL: {{ .Values.kubernetesApi.baseUrl | quote }}
  {{- end }}
  {{if .Values.botfront.cloud }}
  {{if .Values.botfront.cloud.gcpProjectId }}
  GCP_PROJECT_ID: {{ .Values.botfront.cloud.gcpProjectId | quote }}
  {{- end }}
  {{if .Values.botfront.cloud.deploymentEnvironment }}
  CLUSTER_ENVIRONMENT: {{ .Values.botfront.cloud.deploymentEnvironment | quote }}
  {{- end }}
  {{- end }}
{{ end }}
