{{- if .Values.botfront.webhooks.enabled -}}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Values.botfront.webhooks.appName }}
  name: {{ .Release.Name }}-webhooks-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-{{ .Values.botfront.webhooks.appName }}
  type: NodePort
{{ end }}
