{{ if .Values.duckling.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Values.duckling.name }}
  name: {{ .Release.Name }}-duckling-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}-{{ .Values.duckling.name }}
  type: NodePort
{{ end }}
