apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Values.botfront.api.appName }}
  name: {{ .Release.Name }}-api-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.botfront.api.appName }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/botfront-secrets.yaml") . | sha256sum }}{{ include (print $.Template.BasePath "/botfront-api-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-{{ .Values.botfront.api.appName }}
    spec:
      containers:
      - env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              key: MONGO_URL
              name: {{ .Release.Name }}-secrets
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-api-config
            optional: false
        image: {{ .Values.botfront.api.image.name }}:{{ .Values.botfront.version }}
        imagePullPolicy: IfNotPresent
        name: {{ .Release.Name }}-api
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          {{- with .Values.botfront.api.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      restartPolicy: Always
      {{if .Values.botfront.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.botfront.imagePullSecret }}
      {{end }}

