apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Release.Name }}-secrets
type: "Opaque"
data:
  {{- if .Values.botfront.smtpUri }}
  MAIL_URL: {{ .Values.botfront.smtpUri | b64enc | quote }}
  {{- end }}
  MONGO_URL: {{ printf "mongodb://%s:%s@%s/%s?%s" .Values.mongodb.mongodbUsername .Values.mongodb.mongodbPassword .Values.mongodb.mongodbHostsAndPorts .Values.mongodb.mongodbDatabase .Values.mongodb.mongodbQueryString | b64enc | quote }}
  {{- if and .Values.mongodb.mongodbOplogUsername .Values.mongodb.mongodbOplogPassword }}
  OPLOG_URL: {{ printf "mongodb://%s:%s@%s/%s?%s" .Values.mongodb.mongodbOplogUsername .Values.mongodb.mongodbOplogPassword .Values.mongodb.mongodbHostsAndPorts "local" .Values.mongodb.mongodbQueryString | b64enc | quote }}
  {{- end }}
  {{- if .Values.botfront.app.graphQLKey }}
  API_KEY: {{ .Values.botfront.app.graphQLKey | b64enc | quote }}
  {{- end }}
  {{if .Values.kubernetesApi.token }}
  K8S_API_TOKEN: {{ .Values.kubernetesApi.token | toString | b64enc | quote }}
  {{- end }}
  {{if .Values.botfront.licenseKey }}
  LICENSE_KEY: {{ .Values.botfront.licenseKey | toString | b64enc | quote }}
  {{- end }}
  {{if and .Values.portal .Values.portal.slack .Values.portal.slack.clientSecret }}
  SLACK_CLIENT_SECRET: {{.Values.portal.slack.clientSecret | toString | b64enc | quote }}
  {{- end }}
  {{if and .Values.portal .Values.portal.slack .Values.portal.slack.clientID }}
  SLACK_CLIENT_ID: {{.Values.portal.slack.clientID | toString | b64enc | quote }}
  {{- end }}
