apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-{{ .Values.botfront.app.appName }}
  name: {{ .Release.Name }}-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Release.Name }}-{{ .Values.botfront.app.appName }}
  type: NodePort
