{{ range $env, $val := $.Values.environments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}{{ $.Values.appName }}
  name: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}rasa-deployment
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}{{ $.Values.appName }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}{{ $.Values.appName }}
    spec:
      securityContext:
        runAsUser: {{ $.Values.rasa.securityContext.runAsUser }}
        runAsGroup: {{ $.Values.rasa.securityContext.runAsGroup }}
      containers:
      - command:
        - rasa
        - run
        - --enable-api
        {{ if $val.debug -}}
        - --debug
        {{ end -}}
        {{- if $.Values.rasa.authToken }}
        - -t  
        - {{ $.Values.rasa.authToken }}
        {{- end }}
        env:
        - name: BOTFRONT_ENV
          value: {{ $env }}
        {{- if $.Values.botfront.graphQLKey }}
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: API_KEY
              name: {{ $.Release.Name }}-rasa-secrets
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ $.Release.Name }}-rasa-config
            optional: false
        image: {{ $.Values.rasa.image }}
        imagePullPolicy: IfNotPresent
        name: rasa
        ports:
        - containerPort: 5005
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/"
            port: 5005
          initialDelaySeconds: {{ $.Values.rasa.initialProbeDelay }}
          failureThreshold: 10
        resources:
          {{- with $val.resources }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if $.Values.persistenceClaim.enabled }}
        volumeMounts:
        - mountPath: "/app/models"
          name: {{ $.Release.Name }}-rasa-volume
      volumes:
      - name: {{ $.Release.Name }}-rasa-volume
        persistentVolumeClaim:
          claimName: {{ $.Release.Name }}-rasa-volume-claim
      {{- end -}}
    {{if $.Values.rasa.imagePullSecret }}
    imagePullSecrets:
      - name: {{ $.Values.rasa.imagePullSecret }}
    {{end }}
{{- end -}}
