
{{ if .Values.ingress.enabled -}}
{{ range $env, $val := $.Values.environments }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}{{ $.Values.appName }}
  name: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}rasa-ingress
  annotations:
    {{- if $.Values.ingress.nginx.enabled}}
    {{- if $.Values.ingress.nginx.enableSessionAffinity}}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    {{- end}}
    kubernetes.io/ingress.class: nginx
    {{- if $.Values.ingress.nginx.enableSockets}}
    nginx.org/websocket-services: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}rasa-service
    {{- end}}
    {{- with $.Values.ingress.nginx.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- else -}}
    {{ with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end -}}
    {{- end}}
spec:
  rules:
  - host: {{ $val.host }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}rasa-service
          servicePort: 80
        path: {{ if $val.path }}{{ $val.path }}{{ else }}/{{ end }}

  {{ if eq $env "development"}}
  - host: {{ $val.host }}
    http:
      paths:
      - backend:
          serviceName: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}rasa-service
          servicePort: 80
        path: {{ if $val.path }}{{ $val.path }}{{ else }}/{{ end }}
  {{- end}}

  {{ if $val.tlsSecretName -}}
  tls:
  - hosts:
    - {{ $val.host }}
    secretName: {{ $val.tlsSecretName }}
  {{- end -}}
{{- end }}
{{- end }}