apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Release.Name }}-rasa-secrets
type: "Opaque"
data:
  {{- if .Values.botfront.graphQLKey }}
  API_KEY: {{ .Values.botfront.graphQLKey | b64enc | quote }}
  {{- end }}
  {{ - if .Values.rasa.authToken }}
  AUTH_TOKEN: {{ .Values.rasa.authToken  | b64enc | quote }}
  {{- end }}