apiVersion: "v1"
kind: "Secret"
metadata:
  name: {{ .Release.Name }}-rasa-secrets
type: "Opaque"
data:
  {{- if .Values.botfront.graphQLKey }}
  API_KEY: {{ .Values.botfront.graphQLKey | b64enc | quote }}
  {{- end }}