{{- if $.Values.service.enabled -}}
{{ range $env, $val := $.Values.environments }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}{{ $.Values.appName }}
    app: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}{{ $.Values.appName }}
  name: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}rasa-service
spec:
  ports:
  - name: http
    port: {{ $.Values.service.port }}
    protocol: TCP
    targetPort: 5005
  selector:
    app: {{ $.Release.Name }}-{{ if ne $env "default"}}{{ $env }}-{{ end }}{{ $.Values.appName }}
  type: {{ $.Values.service.type }}
{{- end }}
{{- end }}