{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if ne .Release.Namespace "default" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.appName }}
  name: {{ .Release.Name }}-rasa-service
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 5005
  selector:
    app: {{ .Release.Name }}-{{ .Values.appName }}
  type: {{ .Values.service.type }}
{{ end }}